'use client';
import { useEffect, useState } from 'react';
import styles from './pokemon.module.css';
import Link from 'next/link';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const getList = async () => {
	const res = await fetch(
		'https://pokeapi.co/api/v2/pokemon?limit=100&offset=0'
	);
	const list = await res.json();

	return list?.results;
};

export default async function RootLayout({ children }) {
	const list = await getList();

	return (
		<div className={styles.padding}>
			<div className={styles.list}>
				<h3 className={styles.heading}>Pokemon List</h3>
				{list?.length > 0 &&
					list?.map((i, ind) => {
						return (
							<Link href={`/pokemon-detail/${ind + 1}`} key={ind + 1}>
								{i?.name}
							</Link>
						);
					})}
			</div>
			<div className={styles.child}>{children}</div>
		</div>
	);
}
